# Generated by Django 3.1.2 on 2020-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201119_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='cssFile',
            field=models.FileField(blank=True, null=True, upload_to='templates/%m/%d'),
        ),
        migrations.AlterField(
            model_name='template',
            name='htmlFile',
            field=models.FileField(null=True, upload_to='templates/%m/%d'),
        ),
        migrations.AlterField(
            model_name='template',
            name='jsFile',
            field=models.FileField(blank=True, null=True, upload_to='templates/%m/%d'),
        ),
    ]
